name: deploy base64

on:
  pull_request:
    branches:
      - main

jobs:
  bake:
    if: contains(github.event.pull_request.labels.*.name, 'base64')
    name: Build docker image for base64 app and deploy to dokku
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Bake svelte-base64 image and push to github container registry
        uses: docker/bake-action@v4.1.0
        with:
          files: ./docker-bake.hcl
          targets: base64
          push: true
      - name: Deploy svelte-base64 docker image to dokku
        uses: dokku/github-action@v1.4.0
        with:
          git_remote_url: 'ssh://dokku@${{ secrets.DOKKU_HOST }}:22/base64'
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          deploy_docker_image: ghcr.io/${{ github.repository_owner }}/svelte-base64:${{ github.sha }}
