name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  bake:
    name: Build docker image for portfolio-site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Bake image and push to github container registry
        uses: docker/bake-action@v3.1.0
        env:
          API_KEY: ${{ secrets.API_KEY }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        with:
          files: ./docker-bake.hcl
          targets: portfolio
          push: true
      - name: Deploy docker image to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@${{ secrets.DOKKU_HOST }}:22/portfolio'
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          deploy_docker_image: ghcr.io/${{ github.repository_owner }}/portfolio:${{ github.sha }}
