name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  bake:
    name: Build docker image for portfolio-site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/bake-action@v3.1.0
        with:
          files: ./docker-bake.hcl
          targets: portfolio
          push: true
          set: |
            portfolio.args.API_KEY=${{ secrets.API_KEY }}
            portfolio.args.WAKATIME_API_KEY=${{ secrets.WAKATIME_API_KEY }}

  deploy:
    name: Deploy portfolio-site to dokku
    needs: [bake]
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOKKU_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan ${{ secrets.DOKKU_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy app
        run: |
          ssh root@${{ secrets.DOKKU_HOST }} "\\
            docker pull ghcr.io/${{ github.repository_owner }}/portfolio:latest && \\
            docker tag ghcr.io/${{ github.repository_owner }}/portfolio:latest dokku/portfolio:latest && \\
            dokku tags:deploy portfolio latest"
